server.port=8081
spring.ai.mcp.server.name=barbershop-mcp-server

spring.datasource.url=jdbc:postgresql://localhost:5432/Barbershop
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0